# Generated by Django 5.1.4 on 2025-01-25 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_rename_duration_time_service_duration'),
        ('users', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.salon')),
            ],
        ),
    ]
