# Generated by Django 5.1.4 on 2025-01-26 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_service_provider_alter_appointmentslot_date'),
        ('users', '0004_salonemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonemployee',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon', to='scheduler.salon'),
        ),
    ]
