# Generated by Django 5.1.4 on 2025-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_salonemployee_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonemployee',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
