# Generated by Django 5.1.4 on 2025-02-11 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_alter_salon_owner'),
        ('users', '0006_alter_salonemployee_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonemployee',
            name='card_num',
            field=models.CharField(max_length=19, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Card number must be exactly 16 digits.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='salonemployee',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='scheduler.salon'),
        ),
    ]
