# Generated by Django 5.1.4 on 2025-02-22 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_salonemployee_card_num_alter_salonemployee_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonemployee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
