version: '4.2'

services:
  backend:
    build:
      context: ./
    container_name: backend_new
    command: python manage.py runserver
    volumes:
      - ./backend:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env

  tel_bot:
    build: 
      context: ./bot/bot_configs/
    container_name: telegram_bot
    command: py main.py
    volumes:
      - ./bot/bot_configs:/app
    depends_on:
      - backend
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend