# Generated by Django 5.1.2 on 2024-10-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
