# Generated by Django 5.1.2 on 2024-11-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_salon_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Salon Model'},
        ),
        migrations.CreateModel(
            name='SalonAvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=12)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.salon')),
            ],
            options={
                'verbose_name': 'Available time',
            },
        ),
    ]
