# Generated by Django 5.1.3 on 2024-11-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_appointmentslot_remove_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='salon',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.salon'),
        ),
    ]
