# Generated by Django 5.1.3 on 2024-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_appointment_service_alter_appointment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='app_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='app_start',
            field=models.TimeField(null=True),
        ),
    ]
