# Generated by Django 5.1.3 on 2024-12-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_alter_salon_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='end_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='start_time',
            field=models.TimeField(default='8:00'),
        ),
    ]
