# Generated by Django 5.1.3 on 2024-12-23 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_alter_appointmentslot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='end_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
