# Generated by Django 5.1.3 on 2024-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_alter_appointmentslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='day_of_week',
            field=models.CharField(choices=[('شنبه', 'Saturday'), ('یکشنبه', 'Sunday'), ('دوشنبه', 'Monday'), ('سه شنبه', 'Tuesday'), ('چهارشنبه', 'Wednesday'), ('پنجشنبه', 'Thursday'), ('جمعه', 'Friday')], max_length=12, null=True),
        ),
    ]
