# Generated by Django 5.1.4 on 2024-12-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_appointmentslot_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
