# Generated by Django 5.1.4 on 2024-12-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_appointment_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='state',
            new_name='active',
        ),
    ]
