# Generated by Django 5.1.4 on 2024-12-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_rename_state_appointment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='active',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='day_of_week',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=12, null=True),
        ),
    ]
