# Generated by Django 5.1.4 on 2025-01-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_remove_appointment_active_appointmentslot_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='taken',
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0, help_text='Enter the price in Toman (e.g., 50000 for 50,000 Toman)'),
        ),
    ]
