# Generated by Django 5.1.4 on 2025-01-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_remove_appointment_taken_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='duration_time',
            new_name='duration',
        ),
    ]
