# Generated by Django 5.1.4 on 2025-01-26 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_rename_duration_time_service_duration'),
        ('users', '0004_salonemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='users.salonemployee'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
