# Generated by Django 5.1.4 on 2025-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_salon_telegram_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='active',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='status',
            field=models.CharField(choices=[('در انتظار تایید', 'Pending'), ('تایید شده', 'Approved')], default='در انتظار تایید', max_length=20),
        ),
    ]
