# Generated by Django 5.1.4 on 2025-02-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_remove_appointmentslot_active_appointmentslot_status'),
        ('users', '0005_alter_salonemployee_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.salonemployee'),
        ),
    ]
