# Generated by Django 5.1.4 on 2025-02-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_appointmentslot_employee'),
        ('users', '0006_alter_salonemployee_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('پرداخت نشده', 'Not Paid'), ('در انتظار تایید', 'Pending'), ('تایید شده', 'Approved')], default='پرداخت نشده', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='users.salonemployee'),
        ),
    ]
