# Generated by Django 5.1.4 on 2025-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_delete_salonavailabletimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='telegram_chat_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
