# Generated by Django 5.1.6 on 2025-02-24 08:54

import scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_appointment_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receipt_img',
            field=models.ImageField(blank=True, null=True, upload_to=scheduler.models.appointment_images_upload_to),
        ),
        migrations.AddField(
            model_name='appointment',
            name='receipt_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
