# Generated by Django 5.1.6 on 2025-03-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0031_appointment_receipt_img_appointment_receipt_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('رد شده', 'Declined'), ('پرداخت نشده', 'Not Paid'), ('در انتظار تایید', 'Pending'), ('تایید شده', 'Approved')], default='پرداخت نشده', max_length=20),
        ),
    ]
